import java.util.HashMap;

public class findDifference {
    class Solution {
    public char findTheDifference(String s, String t) {
        HashMap<Character, Integer> map = new HashMap<>();
        for (int i = 0; i < s.length(); i++) {
            char ch1 = s.charAt(i);
            map.put(ch1, map.getOrDefault(ch1, 0) + 1);
        }
        for (int i = 0; i < t.length(); i++) {
            char ch2 = t.charAt(i);
            map.put(ch2, map.getOrDefault(ch2, 0) - 1);
            if(map.get(ch2) < 0) {
                return ch2;
            }
        }

        return ' ';
    }
}
}

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"